name=Arduino Q Libraries by Akarita
version=0.1.0
author=Akarita
maintainer=Akarita
sentence=Bare-metal Hardware Abstraction Layer (HAL) for the STM32U585.
paragraph=Low-level library for direct register manipulation (GPIO, Timers, PWM) on the Arduino UNO Q.
category=Device Control
url=https://github.com/Akarita47/ArduinoQLibrariesbyAkarita
architectures=stm32
includes=GPIO/GPIO_configuration.h